spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trading?createDatabaseIfNotExist=true
    username: root
    password: anjusoni
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  file:
    upload:
      photos-output-path: ./uploads

  mail:
    host: smtp.gmail.com
    port: 587
    username: rchitsoni6@gmail.com
    password: gxftmzosjlatuanu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9080

razorpay:
  api:
    key: rzp_test_BbLwkBVuQvM5Zt
    secret: KFtSHEnlNO3BddjweGF6UsNl

stripe:
  api:
    key: 973415413837648

gemini:
  api:
    key: AIzaSyCl99pD1Cgl4PXYq5MEUuZpLOO__5Y_T0U

logging:
  level:
    org.springframework.security: DEBUG
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
    # refresh-token:
    #   expiration: 604800000 # 7 days
